# permissions for end users to view schools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: school-viewer-role
rules:
- apiGroups:
  - esdevops.com
  resources:
  - schools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - esdevops.com
  resources:
  - schools/status
  verbs:
  - get
