# permissions for end users to view students.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: student-viewer-role
rules:
- apiGroups:
  - esdevops.com
  resources:
  - students
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - esdevops.com
  resources:
  - students/status
  verbs:
  - get
